### ISSUE TITLE
Can't resolve all parameters for SlimLoadingBar

### ISSUE THREAD

**Issue by janfriedli** [akserg/ng2-slim-loading-bar#8]
Hi I get the following error:

```
zone.js:461 Unhandled Promise rejection: Error: Can't resolve all parameters for SlimLoadingBar: (?).
	    at new BaseException (http://localhost:4200/vendor/@angular/compiler/src/facade/exceptions.js:27:23)
	    at CompileMetadataResolver.getDependenciesMetadata (http://localhost:4200/vendor/@angular/compiler/src/metadata_resolver.js:314:19)
	    at CompileMetadataResolver.getTypeMetadata (http://localhost:4200/vendor/@angular/compiler/src/metadata_resolver.js:195:26)
	    at CompileMetadataResolver.getDirectiveMetadata (http://localhost:4200/vendor/@angular/compiler/src/metadata_resolver.js:157:28)
	    at eval (http://localhost:4200/vendor/@angular/compiler/src/metadata_resolver.js:230:62)
	    at Array.map (native)
	    at CompileMetadataResolver.getViewDirectivesMetadata (http://localhost:4200/vendor/@angular/compiler/src/metadata_resolver.js:230:27)
	    at RuntimeCompiler._getCompiledTemplate (http://localhost:4200/vendor/@angular/compiler/src/runtime_compiler.js:99:36)
	    at RuntimeCompiler._getTransitiveCompiledTemplates (http://localhost:4200/vendor/@angular/compiler/src/runtime_compiler.js:117:80)
	    at eval (http://localhost:4200/vendor/@angular/compiler/src/runtime_compiler.js:120:77)
	Evaluating http://localhost:4200/main.js
	Error loading http://localhost:4200/main.js ; Zone: <root> ; Task: Promise.then ; Value: Error: Error: Can't resolve all parameters for SlimLoadingBar: (?).
```

I'm using the angular cli and RC4.

My appComponent looks like this:

```javascript
import { Component } from '@angular/core';
import { PersonComponent } from './person/person.component';
import { ROUTER_DIRECTIVES } from '@angular/router';
import {SlimLoadingBar, SlimLoadingBarService,} from 'ng2-slim-loading-bar/ng2-slim-loading-bar';


@Component({
  moduleId: module.id,
  selector: 'app-root',
  templateUrl: 'app.component.html',
  styleUrls: ['app.component.css'],
  directives: [PersonComponent, ROUTER_DIRECTIVES, SlimLoadingBar],
})
export class AppComponent {

  constructor(private slimLoadingBarService:SlimLoadingBarService) { }
  
  startLoading() {
    // We can listen when loading will be completed
    this.slimLoadingBarService.start(() => {
      console.log('Loading complete');
    });
  }
}
```

The template like this: 
```html
<ng2-slim-loading-bar></ng2-slim-loading-bar>
<button (click)="startLoading()">Start Loading</button>
<div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <a [routerLink]="['fichery']" class="navbar-brand"><i class="fa fa-ship" aria-hidden="true"></i> Fichery</a>
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
            <ul class="nav navbar-nav navbar-right">
                <li><a [routerLink]="['events']"><i class="fa fa-calendar" aria-hidden="true"></i> Events</a></li>
                <li><a [routerLink]="['people']"><i class="fa fa-user" aria-hidden="true"></i> People</a></li>
                <li><a [routerLink]="['organizations']"><i class="fa fa-sitemap" aria-hidden="true"></i> Organizations</a></li>
                <li><a [routerLink]="['files']"><i class="fa fa-picture-o" aria-hidden="true"></i> Images</a></li>
                <li><a [routerLink]="['about']"><i class="fa fa-info" aria-hidden="true"></i> About</a></li>
            </ul>
        </div>
    </div>
</div>
<div class="container" style="padding-top: 5em">
    <router-outlet></router-outlet>
</div>
```

and the main.ts: 

```javascript
import { bootstrap } from '@angular/platform-browser-dynamic';
import { enableProdMode } from '@angular/core';
import { AppComponent, environment } from './app/';
import { HTTP_PROVIDERS } from '@angular/http';
import { appRouterProviders } from './app/app.routes';
import { disableDeprecatedForms, provideForms } from "@angular/forms";
import {SlimLoadingBarService} from 'ng2-slim-loading-bar/ng2-slim-loading-bar';



if (environment.production) {
  enableProdMode();
}

bootstrap(AppComponent, [disableDeprecatedForms(), provideForms(), appRouterProviders, HTTP_PROVIDERS, SlimLoadingBarService]);
```

Any idea what might be wrong?

**Comment by Neill83** [comment]
Hi, I'm using angular2 rc5 and it works fine. Maybe try the following things:

1. remove the import for SlimLoadingBarService in main.ts
2. add `providers: [SlimLoadingBarService]` to your appComponent
3. i think its called SlimLoadingBarComponent and not SlimLoadingBar, maybe rename it
4. try it now

For me it works fine.

Regards

**Comment by akserg** [comment]
Hi @janfriedli 
Did you try what @Neill83 suggested? Did it help?

**Comment by janfriedli** [comment]
Hi @akserg 

I'm on holidays right now but I'll try it as soon as I'm back home.

**Comment by akserg** [comment]
I'm closing this one. If the issue still exists - open another one.
